FROM node:18-alpine as build-stage

WORKDIR /client
COPY package.json .
RUN npm install
COPY . .
# EXPOSE 5173
CMD ["npm", "run", "dev"]


# RUN npm run build

# # Stage 2
# FROM nginx:1.17.0-alpine

# COPY --from=build-stage /bezkoder-ui/build /usr/share/nginx/html
# EXPOSE $REACT_DOCKER_PORT

# CMD nginx -g 'daemon off;'