version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: sterdirregistry.azurecr.io/sterilization-directory-server:v2
    ports:
      - "3000:3000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: sterdirregistry.azurecr.io/sterilization-directory-client:v2
    ports:
      - "80:80"
