version: 2.1
executors:
  docker-publisher:
    environment:
      ACR_NAME: $ACR_NAME
      CLIENT_IMAGE_NAME: $ACR_NAME/sterilization-directory-client-fixed
      SERVER_IMAGE_NAME: $ACR_NAME/sterilization-directory-server
    docker:
      - image: cimg/base:2021.04

jobs:
  build-and-test:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set Environment Variables
          command: echo "ACR_NAME=$ACR_NAME" >> $BASH_ENV
      - run:
          name: Build images of services declared in docker-compose.yml
          command: |
            cd server && docker build -t $ACR_NAME/sterilization-directory-server:latest . && cd .. && cd client && docker build -t $ACR_NAME/sterilization-directory-client-fixed:latest .
      # ... rest of your build-and-test steps ...

  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Set Environment Variables
          command: echo "ACR_NAME=$ACR_NAME" >> $BASH_ENV
      - run:
          name: Load archived Docker image
          command: |
            docker load -i /tmp/workspace/client-image.tar
            docker load -i /tmp/workspace/server-image.tar
      - run:
          name: Push Docker Images to Azure Container Registry
          command: |
            # Log in to Azure CLI with service principal credentials (ensure you set these in CircleCI environment variables)
            docker login $ACR_NAME -u $ACR_USERNAME -p $ACR_PASSWORD --tenant $AZURE_TENANT_ID
            # ... rest of your push steps ...

workflows:
  build-master:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: testing
      - publish-latest:
          requires:
            - build-and-test
          filters:
            branches:
              only: testing
